spring.application.name=SMS_Submitter

spring.datasource.url=jdbc:mysql://localhost:3306/SMS_System
spring.datasource.username=root
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=never
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

web2sms.api.url=http://116.203.232.197:8089/web2sms/api
web2sms.account.id=test-account
web2sms.password=test-pass
web2sms.secure.hash=test-hash
web2sms.polling.fixed-delay=10000